### ISSUE TITLE
Need help with few doubts regarding PayPal-node-SDK integration

### ISSUE THREAD

**Issue by mukulgupta2507** [paypal/PayPal-node-SDK#100]
Hi,

I have written a complete question on StackOverflow but none actually responded to that. Can I expect some answers from here ?

http://stackoverflow.com/questions/31369140/integrating-paypal-api-for-recurring-payments

Also, Can I use Vault api from India ?

Thanks

**Comment by mukulgupta2507** [comment]
Any updates on this ?

**Comment by avidas** [comment]
Hey @mukulgupta2507 , we will get back to you with answers soon.

**Comment by mukulgupta2507** [comment]
@avidas I have one more doubt regarding PayPal WP Recurring Payments:
https://developer.paypal.com/webapps/developer/docs/classic/paypal-payments-pro/integration-guide/WPRecurringPayments/

Is there any link for PayPal Standard account as well ? Also, Can anyone please tell me whether PayPal Standard includes recurring Payments ? 

Regarding integration, can you please clarify if the following samples can be used for this ?

I can see many Sample code snippets but not sure what do they mean.

What all Sample code should I look at for integration of Recurring Payments with PayPal Standard/Pro.

https://github.com/paypal/PayPal-node-SDK/tree/master/samples

Few quick doubts:

1. What is the difference between billing plan and billing agreement in https://github.com/paypal/PayPal-node-SDK/blob/master/samples/subscription ?

2. Is https://github.com/paypal/PayPal-node-SDK/tree/master/samples/payment_experience/web_profile only for making customizations in login/pay with PayPal page which appears on redirection ?

3. Let's say I have created a subscription, then for making the actual payment do I need to integrate this https://github.com/paypal/PayPal-node-SDK/tree/master/samples/payment ?

4. If let's say I want to add credit card payment option also in my site's  billing plan, do I need to use this https://github.com/paypal/PayPal-node-SDK/tree/master/samples/credit_card ? Can I use Vault api in this scenario ?

Exactly what all needs to be implemented on my side ?

Thanks

**Comment by ppmtscory** [comment]
@mukulgupta2507 I will try to answer your questions you've just listed out.

1. The Plan is the overall terms of what you want. Many merchants use the same plan for most of their customers so they simply need to create a single plan that will be used amongst multiple agreements.  The agreement is the actual flow the buyer will go through to authorize the terms of the plan.

2. Yes, the Experience APIs allow for the configuration of the PayPal payment page that appears on redirection.

3. If it's set up to do so, the agreement will automatically take the money from the buyer based on the terms set up within the plan & agreement.  You won't need to run a payment call to take the funds.

4. Unfortunately India does not allow for direct credit cards at this time.  Please see the supported country list [here](https://developer.paypal.com/webapps/developer/docs/integration/direct/rest_api_payment_country_currency_support/#direct-credit-card-payments)

**Comment by ppmtscory** [comment]
I think I missed your question about PayPal Standard.  With PayPal Standard, you could create a standard HTML Subscription button that would allow for the recurring payment.  More information can be found in the integration guide [here](https://developer.paypal.com/webapps/developer/docs/classic/products/#wps).

**Comment by mukulgupta2507** [comment]
@ppmtscory 

Following up on the above questions, Can you please cross-verify if I have understood correctly ?

In order to include Pay with PayPal option, I need to first create a billing plan in PayPal. Once I have billingplanId, I can create a billing agreement with user. Also, to cutomize the login page available on redirection, I can use Experience APIs. Correct ? Apart from this I don't need any payment apis, right ?

Also, since the users have flexibility to add/remove certain features from their selected business plan on my website, which results in changing the price of plan for a given month. Can I update my billing plan with the new price ? If yes, do I need to update my billing agreement also for same ?

Also, Can you please give me some idea of the UI flow like this:
https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECUIRequirements/
 
Let's say I have a payment page where user can select Pay With PayPal option. Now once, he clicks on that, he will be redirected to PayPal Login page. Now at what time should I call create Billing Plan/Billing Agreement APIs. Is it before redirecting ? Also, do I need any extra check box to ask user for their consent for recurring billing or will that be taken care by PayPal after redirection ?

Any similar link will be helpful.

Thanks

**Comment by ppmtscory** [comment]
@mukulgupta2507 

Correct.

You can only update a Billing Plan if it's in a CREATED state.  Once a Plan is active, you'll then need to create a new Plan to make changes.  You would then need to create a new Agreement based on that Plan because the subscribers would need to agree to the new payment terms.

The PayPal page after redirection should be similar to the EC pages but you can set up test Plan/Agreements in the Sandbox to be able to see the exact flow.

The redirection URL is provided in the Billing Agreement response.  At this point, you'd already know which Plan to assign to the agreement and would do the Agreement creation and then redirect.  When they click the button, that could kick off the API call for Agreement creation and then you can auto direct with the redirection URL from the response.  The buyer would then see the payment page where they give their approval.  After they return from approval, you'll then need to do the API call to Execute the agreement.

https://developer.paypal.com/webapps/developer/docs/integration/direct/create-billing-plan/
https://developer.paypal.com/webapps/developer/docs/integration/direct/create-billing-agreement/

It's possible that they may be using a different processor (other than PayPal) to do their Credit Card payments.  Also, some PayPal flows don't allow for the use of credit card on the PayPal page so it's possible that they are using one of those flows.

**Comment by mukulgupta2507** [comment]
@ppmtscory 

Thanks a lot for the clarification. I'll integrate PayPal with my website coming weekends. I might have to ask few questions then in case of any difficulty.

**Comment by ppmtscory** [comment]
That's fine @mukulgupta2507.  Feel free to open another issue if you run into any troubles.
