### ISSUE TITLE
Q: Recurring Subscriptions in India

### ISSUE THREAD

**Issue by dezinezync** [paypal/PayPal-node-SDK#109]
Hello,

I've been looking into creating a recurring subscriptions Agreement with the SDK. I've followed the setup example for the same:   
- and have successfully retrieved the `verification_url` and `verification_token`.   
- Upon visiting that URL, I'm asked to login, which I do so with a test-user created on the developer dashboard.   
- Upon successfully authenticating, I receive the following error: 
````
Currently PayPal accounts in India are only able to send payments. This recipient is not eligible to receive funds.
````

**Possible required information**:
Paypal-Node-SDK: latest (871eb67dc3149db152dc8d4d82ee2f25e7ec1994)
Paypal Account Type: Business (verified status)
Limits: Both sending and withdrawal limits are removed after verification. 
Environment: sandbox

Is this error because our Business Account is from India, or possibly something else? Please advise. 
Thank you.

**Comment by avidas** [comment]
For these kind of requests, you'll want to contact [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/app/ask) with your feedback since they are at the best position to answer questions regarding account eligibility.  Because this isn't directly related to the SDK or its usage,  closing it here.

**Comment by dezinezync** [comment]
@avidas thank you for pointing me in the right direction. Cheers.
