### ISSUE TITLE
Billing Plan state remains unchanged and error creating a billing agreement

### ISSUE THREAD

**Issue by iamrudra** [paypal/PayPal-node-SDK#137]
I am trying to understand the Billing Agreement flow and so was trying [this sample](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/subscription/billing_agreements/create.js)

Upon execution, the console shows the following output - 

`Billing Plan state changed to CREATED`

Followed by an error -

```
{ [Error: Response Status : 400]
  response: 
   { name: 'VALIDATION_ERROR',
     details: [ [Object] ],
     message: 'Invalid request - see details',
     information_link: 'https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR',
     debug_id: '4fc24a8d51089',
     httpStatusCode: 400 },
  httpStatusCode: 400 }
```

So **two** things here - The billing plan state is not updated and the billing agreement is not created. I am not sure if these are related in any manner.

**Comment by ppmtscory** [comment]
@iamrudra thank you for reporting this.  There appears to be an issue somewhere in the update process to make the Plan active.  I will research this further and see what's happening.  In the meantime, you can test with the Plans and Agreements separately in lieu of this combined example.

**Comment by ppmtscory** [comment]
@iamrudra I had the sample code updated and it's now working for me just fine.  It seems that the `start_date` in the BA params was causing the error.  Let me know if you run into anything further.

**Comment by iamrudra** [comment]
Thank you for the prompt action. Will try this one more time and let you know.

**Comment by hatzipanis** [comment]
The above is still not working for me. Are we sure it is the `start_date` that is causing the issue? I've tried using moment.js and still not having any luck.

**Comment by ppmtscory** [comment]
@hatzipanis are you using the sample code exactly as is or are you integrating something on your own?  I've used the sample code solely and am able to process the Agreement successfully (after the update to `start_date` was pushed).  In the logging, it says the plan is in `CREATED` state but if you do a GET call on the plan, prior to creating the agreement, you will see that it is actually set to `ACTIVE`.  I'm assuming this may be to where this logging statement is included in the code itself but I haven't looked into that yet since the Plan is being activated appropriately.

**Comment by hatzipanis** [comment]
@ppmtscory thanks for the quick reply. I've solved this by using moment.js and setting a date in the future (which I hadn't done at the time of my last comment). I couldn't get this to work using the sample code in a slightly modified way in my application. I'll put the error down to something in my code though. Cheers!
