### ISSUE TITLE
how to get token? (for issue #143)

### ISSUE THREAD

**Issue by benzmuircroft** [paypal/PayPal-node-SDK#144]
Not sure why @bluk closed issue #143..

```
    {
    url:`https://api.sandbox.paypal.com/v1/oauth2/token?`+`xxxxxx_client_id_xxxxxx`+`=`+`xxxxxx_client_secret_xxxxxx`
,   headers:{'Content-Type':`application/json`,'Accept-Language':`en_US`}
    }
```

gives me

data `undefined` and `code` 200

as a response with a GET request

Is it something to do with the equals character? I think I'm somehow suppose to be using a semicolon instead but I've got no clue what the key name would be in that case

```
something=xxxxxx_client_id_xxxxxx:xxxxxx_client_secret_xxxxxx
``` 

semicolon ----------------------------------------^ ?

**Comment by bluk** [comment]
I reopened #143, so I'll close this as a dupe. I left a [comment as well](https://github.com/paypal/PayPal-node-SDK/issues/143#issuecomment-203084662) with some info about the request you should be using (and if you can answer what code/client/library you're trying to use in #143 , that would be helpful since I'm not sure what the JSON you're pasting correlates to).
