### ISSUE TITLE
An internal service error has occurred

### ISSUE THREAD

**Issue by just4give** [paypal/PayPal-node-SDK#145]
I am constantly getting below error since last 3-4 hours. Everything worked fine till yesterday evening when I tested last. I tried both credit card and paypal payment modes. Used different card numbers as well but every time got same error.  Is there any issue going on with sandbox api  ? 

{
	"status": 500,
	"duration_time": 294,
	"body": {
		"message": "An internal service error has occurred",
		"debug_id": "bc34eba185f7b",
		"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR",
		"name": "INTERNAL_SERVICE_ERROR"
	},
	"additional_properties": {},
	"header": {
		"Content-Length": "212",
		"Content-Language": "*",
		"CORRELATION-ID": "bc34eba185f7b",
		"Date": "Wed, 30 Mar 2016 18:57:34 GMT",
		"Connection": "close",
		"Paypal-Debug-Id": "bc34eba185f7b",
		"PROXY_SERVER_INFO": "host\\u003dslcsbplatformapiserv3001.slc.paypal.com;threadId\\u003d775",
		"Content-Type": "application/json"
	}
}

**Comment by ppmtscory** [comment]
Hi all, sandbox appears to be experiencing some downtime. We're tracking the issue over at [paypal/PayPal-PHP-SDK#531](https://github.com/paypal/PayPal-PHP-SDK/issues/531), so I'm going to close this one as a duplicate so that we don't have multiple threads. We'll provide back information as we can there.

**Comment by just4give** [comment]
Thanks a lot for quick response
