### ISSUE TITLE
How to check whether the amount sent to paypal id using payouts is valid paypal id or not?

### ISSUE THREAD

**Issue by uditkumawat** [paypal/PayPal-node-SDK#208]
### General Information

- Mode (Live): Live
- PayPal-Debug-ID(s) (from any logs):
- Version of node.js used: 4.4.7
- SDK Version: latest

### Issue Description
I am sending payment using payout API in live environment but I have to check whether the paypal id is valid or not ?

Is there any API for that verification ?

**Comment by bluk** [comment]
[GetVerifiedStatus_API_Operation](https://developer.paypal.com/docs/classic/api/adaptive-accounts/GetVerifiedStatus_API_Operation/) may help but it is part of the Adaptive Payments API which is [now on a limited release.](https://devblog.paypal.com/adaptive-payments-limited-release/). The reason why there isn't an API is because it could be used for abuse.
