### ISSUE TITLE
Connection issue keeps happening

### ISSUE THREAD

**Issue by tzookb** [paypal/PayPal-node-SDK#229]
I have been trying to figure it out for the past day and half, any help will be appreciated.

I work on my localhost, in vagrant machine (10.0.67.67:3000)

and I try to create a simple subscription just like in the example.

But I keep getting this error: 

    "Error: write ECONNRESET"

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs):
- Version of node.js used: 0.10.40
- SDK Version:

**Comment by bluk** [comment]
@tzookb Are you able to make long lived connections to other sites without a `ECONNRESET`? Furthermore, have you tried upgrading to the latest supported version of Node.js (0.10.x was just ended in Oct 2016)?

You will probably need to reach out to Vagrant support or your VM provider since this seems to be a networking stack issue which is beyond the scope of these SDKs.

**Comment by tzookb** [comment]
Thanks @bluk 

Yes I had many service integrated with my vagrant machines :/

and unfortunately I cant upgrade the node version right now, I wish I could...

any ideas? maybe because of localhost or something? should I approve my localhost on paypal or something just like on facebook api?

**Comment by bluk** [comment]
@tzookb I don't believe you need to whitelist `localhost` specifically for PayPal API calls. Have you tried using the SDK outside of Vagrant to see if you can reproduce the issue (just to make sure it is the Vagrant setup that is causing the problem)?

If it is a Vagrant/VM issue, just from personal experience, I've had to change the networking stack from bridge to NAT or some other combination to get a stable network connection on some VMs. It is really dependent on the combination of VM guest and host systems though and the configurations between them.
