### ISSUE TITLE
Your npm tags are broken

### ISSUE THREAD

**Issue by oliviertassinari** [paypal/PayPal-node-SDK#323]
```sh
> npm info paypal-rest-sdk
...
'dist-tags': { latest: '2.0.0-beta.1', beta: '2.0.0-beta.0' },
...
```

**Comment by oliviertassinari** [comment]
Shouldn't it be?
```sh
'dist-tags': { latest: '1.8.1', next: '2.0.0-beta.1' },
```

**Comment by bluk** [comment]
Thanks for the report. This should be corrected now. There appears to be a [mix usage of `next` versus `beta`](https://docs.npmjs.com/cli/dist-tag#purpose) across npm. I think signifying it is a beta might be more appropriate at this time due to getting feedback and still making possible breaking changes. However, if there's a specific reason for `next`, please let us know. Thanks.

**Comment by oliviertassinari** [comment]
@bluk using `next` is a convention I have often seen. But maybe it's not. As the npm documentation is using [`beta`](https://docs.npmjs.com/getting-started/using-tags). Thank you :).
