### ISSUE TITLE
Build issues with configure.js

### ISSUE THREAD

**Issue by donhmorris** [paypal/PayPal-node-SDK#353]
### General information
Module loading problem

* SDK/Library version: 1.8.1
* Environment: All
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: Tyepscript 2.4.2 Angular 4

### Issue description
These 2 lines in configure.js cause compiler and module loading errors during my build. They seem unnecessary and my build works fine if I remove them.

var sdkVersion = exports.sdkVersion = require('../package').version;
var userAgent = exports.userAgent = 'PayPalSDK/PayPal-node-SDK ' + sdkVersion + ' (node ' + process.version + '-' + process.arch + '-' + process.platform  + '; OpenSSL ' + process.versions.openssl + ')';

**Comment by xiaoleih41** [comment]
Did you use our [newer version of SDK](https://github.com/paypal/PayPal-node-SDK/tree/2.0-beta)?

**Comment by bluk** [comment]
This SDK is intended only for Node.js usage on a secure server (since you are exposing your client IDs and secrets to this SDK). Are you trying to use it in a browser?

**Comment by donhmorris** [comment]
Developing in browser but want to move it firebase cloud functions. Any recommendations for developing and deploying in firebase cloud functions?

Regards,
Don Morris

On Mar 26, 2018, at 10:29 AM, Bryant Luk <notifications@github.com<mailto:notifications@github.com>> wrote:


This SDK is intended only for Node.js usage on a secure server (since you are exposing your client IDs and secrets to this SDK). Are you trying to use it in a browser?

**Comment by bluk** [comment]
This SDK does not officially support Firebase. I would suggest running on the platform itself instead of a browser since Firebase may have some restrictions/limitations on functionality. Also, ensure that no one else has access to your client secrets or they may be able to create/refund transactions and other things using your credentials. Feel free to leave a comment with any issues encountered, but there is currently not a plan to support Firebase.
